### ISSUE TITLE
How to prevent DJLint for linting non-jinja files?

### ISSUE THREAD

**Issue by mousetail** [djlint/djlint-vscode#1049]
Currently, DJLint seems to give error for every file, even though I have configured it so it should lint only `jinja-html`.

My configuration is this:
```json
{
  "djlint.pythonPath": ".venv/bin/python",
  "files.associations": {
    "*.jinja.html": "jinja-html"
  },
  "djlint.formatCss": true,
  "djlint.formatAttributeTemplateTags": true,
  "djlint.formatJs": true,
  "djlint.enableLinting": true,
  "[jinja-html]": {
    "editor.defaultFormatter": "monosans.djlint"
  },
  "djlint.configuration": ".djlintrc"
}
```
But it's still linting `.rs` and `.json` files

**Comment by monosans** [comment]
You enabled `djlint.enableLinting` globally, that's the reason. You should enable it separately for each language, as you did with “[jinja-html]”. It is already enabled for jinja by default.

**Comment by mousetail** [comment]
@monosans Is it possible to hide the option in the GUI? This seems like an option that should only be set in the JSON, since setting globally seems always a mistake
