### ISSUE TITLE
Buggy behaviour when commenting and uncommenting via Toggle Line Comment vscode shortcut in Django HTML.

### ISSUE THREAD

**Issue by suspiciousRaccoon** [djlint/djlint-vscode#671]
Sometimes when I comment html code and try uncommenting it djlint fails to uncomment it and adds more comment tags.

Example:
```html
<svg xmlns="http://www.w3.org/2000/svg"
     width="16"
     height="16"
     fill="currentColor"
     class="bi bi-file-earmark-text"
     viewBox="0 0 16 16">

```
If i select the 7th line a press shift and up until I'm at the 1st line, and then use the Toggle Line Comment shortcut (in my case ctrl + /) it comments the code correctly, but if I press the keybind again, it proceeds to add more tags.
![image](https://github.com/djlint/djlint-vscode/assets/127566947/510fcc00-1b29-4863-8f2a-537b0cf181ef)
![image](https://github.com/djlint/djlint-vscode/assets/127566947/6def0201-9f4c-445b-a5f9-583ef8653346)
This also happens if add another line at the top and select from the 1st line and the 8th line:
![image](https://github.com/djlint/djlint-vscode/assets/127566947/63c4f25a-021c-406c-98fa-f28af08475f0)
If I select the code action "comment selection" it also gets buggy.
![image](https://github.com/djlint/djlint-vscode/assets/127566947/c05bc98a-e4fc-4e6d-a44c-f7b5cfdd850c)
When I try using the shortcut it adds a new comment tag and removes it if the shortcut is pressed again.
![image](https://github.com/djlint/djlint-vscode/assets/127566947/24731506-6047-4297-b37d-7a6c3114d84c)
This also happens if I select from the end of the tag instead of from line 7.

**Comment by monosans** [comment]
Hi. djLint has nothing to do with this. It is handled by another extension.
