### ISSUE TITLE
Inconsistent indentation within VSCode and using pre-commit

### ISSUE THREAD

**Issue by sergiopmdeveloper** [djlint/djlint-vscode#862]
Currently the VSCode extension does not support the indentation that is set in the djlint configuration, which means that when the file is formatted, all the rules are applied except the indentation rule. However, it is applied in the pre-commit because it obviously calls the djlint executable directly without the VSCode intermediary. This is somewhat annoying because the pre-commit will always fail because of the indentation due to formatting on save or whenever the user wants to do it but using the VSCode extension does not apply the indentation and the pre-commit does.

**Comment by monosans** [comment]
Disable `djlint.useEditorIndentation`
